# my global config
global:
  scrape_interval: 5s
  evaluation_interval: 10s

scrape_configs:
  - job_name: statsd_exporter
    static_configs:
      - targets: ['statsd_exporter:9102']
        labels:
          exporter: 'statsd'